import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "@/commons/providers/auth/auth.provider";
import { AuthGuard } from "@/commons/providers/auth/auth.guard";
import { ModalProvider } from "@/commons/providers/modal/modal.provider";
import { NextThemesProvider } from "@/commons/providers/next-themes/next-themes.provider";
import { ReactQueryProvider } from "@/commons/providers/react-query/react-query.provider";
import Layout from "@/commons/layout";

const pretendard = localFont({
  src: [
    {
      path: "./fonts/Pretendard-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Pretendard-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="antialiased">
        <AuthProvider>
          <ReactQueryProvider>
            <NextThemesProvider>
              <ModalProvider>
                <AuthGuard>
                  <Layout>
                    {children}
                  </Layout>
                </AuthGuard>
              </ModalProvider>
            </NextThemesProvider>
          </ReactQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
